### ISSUE TITLE
Document how to debug tools

### ISSUE THREAD

**Issue by BigRoy** [mindbender-studio/core#156]
# Problem

I'm having some issues defining how to quickly get up and running to start debugging a tool. What's the proposed workflow to run, for example, the `mindbender.tools.manager`.

I've currently:

1. Set up a database (running mongodb server on localhost)
2. Set up python dependencies

Then I run:

```python
import mindbender.tools.manager as app
app.show(debug=True)
```

Resulting in error:

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Work\pipeline\mindbender\git\mindbender-setup\git\mindbender-core\mindbender\tools\manager\app.py", line 392, in show
    window.refresh()
  File "C:\Work\pipeline\mindbender\git\mindbender-setup\git\mindbender-core\mindbender\tools\manager\app.py", line 269, in refresh
    for container in api.registered_host().ls():
AttributeError: 'NoneType' object has no attribute 'ls'
```

Which made me try to register the _debug host_ prior to this.

```python
import mindbender.pipeline as pipeline
host = pipeline.debug_host()
pipeline.install(host)
```

That resulted in error:

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Work\pipeline\mindbender\git\mindbender-setup\git\mindbender-core\mindbender\pipeline.py", line 44, in install
    "%s missing from environment" % ", ".join(missing)
AssertionError: MINDBENDER_PROJECT, MINDBENDER_ASSET missing from environment
```

I believe from here it's a matter to set up an example project; like create a new project and load that up; and setting the environment variables. I hope to find some time soon to continue playing but I thought documenting here what "happened" as I quickly tried to debug/test some of the tools in isolation what held me back from being able to do so. 

> Note: Some of this might be related to #135 

---

I'll try to document the steps required to get up and running whenever I find some more time to play with this.

**Comment by mottosso** [comment]
Excellent question.

The workflow for running tools in isolation got more complicated with the introduction of the database. They all currently depend in one, which is less than ideal. And the more demanding the apps get, the tighter the coupling will be between application and data.

Currently the workflow is this. 

```bash
$ python -m mindbender manager
```

The same then goes for `loader` and `creator`.

What I'd like to have happen is to find what data is essential to the operation of each app and then mock those parts. All I/O with the database is currently going through io.py which is a thin wrapper around native mongodb commands. Those can be mocked bit ideally none of the apps would rely on mongo either, but rather an abstraction on top of mongo. Like `get_assets()` as opposed to `io.find ({"type": "asset"})`,  which, though short and clear, may be difficult to abstract as-is or to transition from should we choose a different database backend. (I'm keeping my eyes on Rethink especially, for their real-time features)

So long as the above interface to running individual tools remain as the example above, the sky's the limit on hoe we mock things.
